trial_attachments:
  config:
    include_match: '.+\.ya?ml$'
    exclude_match: '\/vendor\/|\/cider-ci\/'
    content_type: text/yaml
  logs:
    include_match: '\/logs?\/.+\.log$'
    content_type: text/plain


scripts:
  configure:
    body: |
      #!/usr/bin/ruby
      require 'yaml'

      ### CIDER-CI Service Configuration ######################################

      config = YAML.load_file 'resources_dev/config_defaults.yml'

      # database
      config['database']['user']= ENV['PGUSER']
      config['database']['password']= ENV['PGPASSWORD']
      config['database']['subname']= "//localhost:#{ENV['PGPORT']}/#{ENV['DATABASE_NAME']}"

      # storage
      config['services']['server']['http']['port']= Integer(ENV['SERVER_HTTP_PORT'])
      config['services']['server']['http']['host']= 'localhost'
      config['services']['server']['nrepl']['enabled']= false

      # write config
      File.open('config/config.yml','w') { |file| file.write config.to_yaml }

