include:
  - cider-ci/task-components/deps-tools-install.yml

trial_attachments:
  config:
    include_match: '.*(config|resource).+\.ya?ml$'
    exclude_match: '\/vendor\/|\/cider-ci\/'
    content_type: text/yaml
  logs:
    include_match: '\/logs?\/.+\.log$'
    content_type: text/plain

scripts:
  ci-server_configure:
    start_when:
      'deps and tools are installed':
        script_key: ci-server_install-all-deps-and-tools
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $CIDER_CI_TEST_SERVER_DIR
      ./cider-ci/scripts/configure-server.rb

