trial_attachments:
  config:
    include_match: '.+\.ya?ml$'
    exclude_match: '\/vendor\/|\/cider-ci\/'
    content_type: text/yaml
  logs:
    include_match: '\/logs?\/.+\.log$'
    content_type: text/plain


scripts:
  configure:
    start_when:
      'bundled':
        script_key: ruby-setup
    body: cider-ci/bin/server-test-env-setup.rb

