include:
  - cider-ci/task-components/configure.yml
  - cider-ci/task-components/uberjar-build.yml
  - cider-ci/task-components/database.yml

scripts:

  ci-server_ready-to-run:
    start_when:
      database is ready:
        script_key: database_is_ready
      service is configured:
        script_key: ci-server_configure
      jar has been built:
        script_key: ci-server_uberjar-build
    body: exit 0

  ci-server_run:
    start_when:
      service is ready to run:
        script_key: ci-server_ready-to-run
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $CIDER_CI_TEST_SERVER_DIR
      java -jar cider-ci.jar server run


  ci-server_is-running:
      timeout: 15 seconds
      environment_variables:
        STATUS_URL: http://localhost:{{CIDER_CI_TEST_SERVER_HTTP_PORT}}/cider-ci/client/status
      body: |
        #!/usr/bin/env bash
        set -euo pipefail
        cd $CIDER_CI_TEST_SERVER_DIR
        until curl --silent --fail \
          --user test-check-is-running:service-secret \
          -H 'Accept: application/json' \
          -I "${STATUS_URL}";  do
          sleep 1;
        done
      start_when:
        service is executing:
          script_key: ci-server_run
          states: [executing]


  test:
    start_when:
      ci-server is running:
        script_key: ci-server_is-running


  ci-server_shutdown:
    timeout: 3 Seconds
    start_when:
      'test is in terminal state':
        script_key: test
        states: [aborted, defective, passed, failed, skipped]
    environment_variables:
      SHUTDOWN_URL: http://localhost:{{CIDER_CI_TEST_SERVER_HTTP_PORT}}/cider-ci/shutdown
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $CIDER_CI_TEST_SERVER_DIR
      curl -I -X POST --silent \
        --user shutdown:service-secret \
        -H 'Accept: application/json' \
        "${SHUTDOWN_URL}"


  database_drop:
    start_when:
      server run is terminal:
        script_key: ci-server_shutdown
        states: [aborted, defective, passed, failed, skipped]



