windows:
  2:
    name: server
    command: |
      lein do clean, repl
    post_command_send_keys: |
      (-main "server" "run")
  3:
    name: figwheel
    command: |
      # give lein clean from window 3 some time before we start figwheel
      # fswatch -o src/* -o project.clj | xargs -I {} lein figwheel
      sleep 5
      lein figwheel
  5:
    name: database
    command: |
      psql -d cider-ci_v5
  6:
    name: github-mock
    command: |
      export GITHUB_API_MOCK_PORT=8998
      bundle exec ruby github_api_mock.rb -p ${GITHUB_API_MOCK_PORT}
  7:
    name: test
    command: |
      export GITHUB_API_MOCK_PORT=8998
      export RAILS_ENV=test
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log

  9:
    name: executor
    command: |
      set ­euxo
      mkdir -p ../executor
      lein run -- executor -c ../executor/config.yml write-default-config -f
      lein do run -- executor -c ../executor/config.yml run --nrepl-enabled yes -t TestExecutor1234

  10:
    name: sass
    command: |
      sass --watch resources/all/public/css/site.sass:resources/all/public/css/site.css
