name: CI/ZHdK/ci/server
windows:
  2:
    name: server
    command: |
      ./bin/server-run
  3:
    name: figwheel
    command: |
      # give lein clean from window 3 some time before we start figwheel
      lein figwheel
  5:
    name: database
    command: |
      psql -d cider-ci_v4
  6:
    name: github-mock
    command: |
      export GITHUB_API_MOCK_PORT=8998
      bundle exec ruby github_api_mock.rb -p ${GITHUB_API_MOCK_PORT}
  7:
    name: test
    command: |
      export GITHUB_API_MOCK_PORT=8998
      export RAILS_ENV=test
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log

  9:
    name: executor
    command: |
      set ­euxo
      mkdir -p ../executor
      lein run -- executor -c ../executor/config.yml write-default-config -f
      lein do run -- executor -c ../executor/config.yml run --nrepl-enabled yes -t TestExecutor1234

