jobs:

  unit-tests:
    name: Run tests
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        git_options:
          submodules:
            include_match: ^.*$
        traits:
          - asdf
        body: |
          #!/usr/bin/env bash
          set -euo pipefail
          ./bin/lein deps
          ./bin/lein test $CIDER_CI_TASK_FILE
      generate_tasks:
        include_match: src/test/.*.clj

  uberjar:
    name: build uberjar
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        git_options:
          submodules:
            include_match: ^.*$
        traits:
          - asdf
      tasks:
        uberjar:
          scripts:
            uberjar:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                ./bin/lein deps
                ./bin/uberjar

  specs:
    name: Run specs
    depends_on: &SPEC_DEPENDENTS
      uberjar passed:
        type: job
        job_key: uberjar
        states: [passed]
    run_when: *SPEC_DEPENDENTS
    include: cider-ci/jobs/specs.yml

