# Cider-CI 5.0.0-26 Default Executor Configuration
#
# Some of these defaults depend on the environment.
# We recommend to create a configuration file based on this file
# but only including those keys/values which are intended to be 
# overridden.
# The default configuration will be merged with the configuration
# given in the config-file. See also 'deep-merge' in the documentation.
#
accepted_repositories: []
basic_auth: {username: nx-07288.home, password: null}
default_script_timeout: 3 Minutes
exec_user: {name: null, password: null}
hostname: nx-07288.home
http: {port: 8883, host: localhost, enabled: false}
max_load: 8
name: DemoExecutor
nrepl: {port: 7883, bind: localhost, enabled: false}
reporter: {max-retries: 10, retry-factor-pause-duration: 3 Seconds}
repositories_dir: /Users/thomas/Programming/CIDER-CI/cider-ci_v4/server/tmp/executor_repositories
secret: master-secret
self_update: false
server_base_url: http://localhost:8888
server_secret: master-secret
service: executor
services:
  dispatcher:
    http: {context: /cider-ci, sub_context: /dispatcher, ssl: false}
sync_interval_pause_duration: 1 Second
temporary_overload_factor: 1.99
tmp_dir: tmp
traits_files: []
trial_retention_duration: 30 Minutes
windows: {fsi_path: 'C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe'}
working_dir: /Users/thomas/Programming/CIDER-CI/cider-ci_v4/server/tmp/working_dir
