source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara', '~> 3.38.0'
gem 'cider_ci-support', '3.2'
gem 'factory_bot'
gem 'faker'
gem 'haml'
gem 'json_roa-client', '=2.0.0.pre.beta.6'
gem 'pg', platform: 'mri'
gem 'poltergeist'
gem 'pry'
gem 'pry-nav'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver', '~> 3.14'
gem 'sequel'
gem 'sinatra'
gem 'rexml'
