source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara'
gem 'cider_ci-support', '3.2'
gem 'factory_girl'
gem 'faker'
gem 'haml'
gem 'json_roa-client', '=2.0.0.pre.beta.6'
gem 'pg', platform: 'mri'
gem 'pry'
gem 'pry-nav'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
gem 'sequel'
gem 'sinatra'
gem 'puma'
