database:
  adapter: "postgresql"
  classname: "org.postgresl.Driver"
  subname: "//localhost:5432/cider-ci_v4"
  subprotocol: "postgresql"
  user: cider-ci
  password: secret
  max_pool_size: 5

github_authtoken: NULL

hostname: localhost

secret: master-secret

basic_auth:
  password: service-secret

session:
  secret: session-secret
  max_lifetime: 7 Days

server_base_url: http://localhost:8888

services:

  server:

    http:
      host: 127.0.0.1
      port: 8881
      ssl: false

    nrepl:
      port: 7881
      bind: "127.0.0.1"
      enabled: true

    repositories:
      path: "./tmp/repositories"

    stores:

      - url_path_prefix: "/trial-attachments"
        file_path: "./tmp/storage/trial-attachments"
        db_table: trial_attachments

      - url_path_prefix: "/tree-attachments"
        file_path: "./tmp/storage/tree-attachments"
        db_table: tree_attachments
